# Generated by Django 5.2.1 on 2025-05-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=45, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'catagories',
                'db_table': 'catagory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ru', models.CharField(max_length=36, unique=True)),
                ('word_uz_k', models.CharField(max_length=36, unique=True)),
                ('word_uz_l', models.CharField(max_length=36, unique=True)),
                ('word_en', models.CharField(max_length=36, unique=True)),
                ('word_tr', models.CharField(max_length=36, unique=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dict.catagory')),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
                'db_table': 'dictionary',
                'managed': True,
            },
        ),
    ]
